### PR TITLE
No random

### PR DESCRIPTION
**Pull request by KaiLangen**
Introduced thread-serial randomized  generation of events before thread-parallel part of simulation. Retest this please

### CODE REVIEW

**Comment by KaiLangen** [comment]
Retest this please

**Comment by KaiLangen** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by tribal-tec** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
Retest this please

**Comment by timocafe** [comment]
Retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
retest this please

**Comment by timocafe** [comment]
Retest this please

**Comment by timocafe** [comment]
Retest this please

**Pull request closed without merging**
